### ISSUE TITLE
Wrong process representation

### ISSUE THREAD

**Issue by adrienkohlbecker** [kennethkalmer/ruote-kit#24]
I'm having an issue with the representation of our process, the image is not correct. Our process is represented like this: 
https://www.dropbox.com/s/prweu0rvy3mq04i/Screen%20Shot%202013-04-16%20at%2010.02.21.png

And the process definition is:

``` ruby
pdef = Ruote.process_definition :name => 'receipt_processing_skerou' do

  concurrent_iterator :on_field => 'receipt_subpicture_uuids', :to_var => 'uuid' do
    synchronize :key => "uploaded_subpicture-${v:uuid}"

    set :field => 'uuid', :value => "${v:uuid}"
    set :field => 'inbox_path', :value => "inbox/${f:editor_inbox}/${v:uuid}.jpg"

    process_image
    store_image_processing
    create_line_instances

    concurrent_iterator :on_field => 'textons', :merge_type => :union do
      read_texton :texton_index => '${v:ii}'
    end

    store_textons_processing
    store_ocr_interpretations

  end

  ocr_analysis

end
```

**Comment by jmettraux** [comment]
Transferred to https://github.com/jmettraux/ruote-fluo/issues/5

**Comment by jmettraux** [comment]
Have to upgrade ruote-kit to the new SVG ruote-fluo, that fixes this issue.

**Comment by jmettraux** [comment]
Hello,

I moved ruote-kit to use the new ruote-fluo which is SVG-based instead of Canvas-based.

There are still issue, especially with the ruote-fluo-editor, but mostly, it looks OK. The new ruote-fluo since it's SVG-based is styled via its own CSS so appearance can be made better...

Some expressions, like concurrent-iterator, have no specific renderer, they fall back to the default renderer, which sometimes is not satisfying, but, hopefully, the new ruote-fluo code is easier to grasp.

Suggestions, PRs, etc are welcome.

https://github.com/kennethkalmer/ruote-kit/commit/5ab230d6d99234db810e39a94918a464c00c20b5
https://github.com/jmettraux/ruote-fluo
https://github.com/jmettraux/ruote-fluo/issues/6

I'll close this issue when the ruote-fluo-editor behaves in ruote-kit.

**Comment by adrienkohlbecker** [comment]
Thanks for the fix, by the way !
We implemented this in our system this week and it's looking good. Still there are some small issues, namely:
- The process representation is taking all the screen estate, but maybe that's what you refered to in your comment about CSS, I'll have a look
- There are no pins that show where the process currently is

Nothing really blocking, but I thought I'd let you know.

**Comment by jmettraux** [comment]
no pins: opened https://github.com/kennethkalmer/ruote-kit/issues/25 for it

real estate: that's a problem. We could a) fold by default b) only show the process definition when required (and thus in its own [whole] screen c) {insert other solution here}. Not an easy one.

**Comment by adrienkohlbecker** [comment]
Or maybe just display it below the actions so you don't have to scroll ?

**Comment by jmettraux** [comment]
Sorry, I don't understand. The actions are on the left, the diagram is on the right, right?

**Comment by adrienkohlbecker** [comment]
No, for large processes they are below the diagram, here is an example from one of our processes

![screen shot 2013-05-02 at 13 49 52](https://f.cloud.github.com/assets/70469/453602/775922d4-b31e-11e2-8fcf-8a94c436b2f1.png)

**Comment by jmettraux** [comment]
Ah, got it, thanks!

My initial idea was to scale down the diagram. Clicking on it would reveal it at max size. Let me try something...
